// Generated by CoffeeScript 1.4.0
var Path, SCRIPTS_LIB;

Path = require('path');

SCRIPTS_LIB = Path.resolve(__dirname, '../node_modules/hubot-scripts/src/scripts');

module.exports = function(robot) {
  return robot.respond(/learn\ (\w+)*/i, function(msg) {
    var name, script, scriptPath, sctrip;
    name = msg.match[1].trim();
    if (Path.extname(name)) {
      sctrip = name;
    } else {
      script = name + 'coffee';
    }
    scriptPath = Path.join(SCRIPTS_LIB, script);
    return Path.exists(scriptPath, function(exists) {
      if (!exists) {
        return msg.send("Script " + name + " not found at " + scriptPath + ".\nYou can find all scripts at http://hubot-script-catalog.herokuapp.com/.\nSome of them might not been working here through.");
      } else {
        robot.loadFile(SCRIPTS_LIB, name);
        return msg.send("Now I know how to do " + name);
      }
    });
  });
};
